<?php
return array (
  1 => 
  array (
    'id' => '1',
    'catid' => '9',
    'typeid' => '0',
    'title' => '測試一下',
    'style' => '',
    'thumb' => '',
    'keywords' => '測 試 一測試一下下',
    'description' => '測試一下測試一下測試一下',
    'posids' => '0',
    'url' => 'http://localhost/index.php?m=content&c=index&a=show&catid=9&id=1',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1375883914',
    'updatetime' => '1376479690',
    'hitsid' => 'c-1-1',
    'views' => '6',
    'yesterdayviews' => '2',
    'dayviews' => '1',
    'weekviews' => '3',
    'monthviews' => '6',
  ),
  34 => 
  array (
    'id' => '34',
    'catid' => '9',
    'typeid' => '0',
    'title' => '冷下滑冷下滑冷下滑冷下滑',
    'style' => '',
    'thumb' => '',
    'keywords' => '下滑 下滑 下滑',
    'description' => '冷下滑冷下滑冷下滑冷下滑冷下滑冷下滑冷下滑',
    'posids' => '0',
    'url' => 'http://localhost/index.php?m=content&c=index&a=show&catid=9&id=34',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1376479823',
    'updatetime' => '1376479849',
    'hitsid' => 'c-1-34',
    'views' => '1',
    'yesterdayviews' => '0',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '1',
  ),
);
?>